<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Strativ\Blog\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
$post = $postVm->getDetail();
?>

<div class="blog-post-detail">
    <h1> <?= $escaper->escapeHtml($post->getTitle()) ?> </h1>
    <p><em> <?= __('Created at: %1', $post->getCreatedAt()) ?></em></p>
    <p> <?= __($escaper->escapeHtml($post->getContent(), ['em', 'p', 'strong'])) ?> </p>
</div>
